name: CI

on:
  - workflow_dispatch
  - push

jobs:
  Build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu
          - macos
        compiler:
          - cc: gcc
            cxx: g++
          - cc: clang
            cxx: clang++
        exclude:
          - os: macos
            compiler: { cc: gcc, cxx: g++ }
    runs-on: ${{ matrix.os }}-latest
    env:
      CC: ${{ matrix.compiler.cc }}
      CXX: ${{ matrix.compiler.cxx }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        if: ${{ matrix.os == 'macos' }}
        run: |
          echo "ZLIB_ROOT=$(brew --prefix zlib)" >> $GITHUB_ENV
      - name: Configure
        run: cmake -B build
      - name: Build
        run: cmake --build build
